import Head from 'next/head';
import styled from 'styled-components';
import { Hotels } from 'components/pages/hotels/hotels';

export const Container = styled.div`
  min-height: 100vh;
  height: 100vh;
  padding: 1rem;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hotels/>
    </Container>
  );
}
